### ISSUE TITLE
프로젝트 README.md를 작성한다. 

### ISSUE THREAD

**Issue by zldnlto** [FRONTENDSCHOOLPLUS2/HighlighTalk#135]
### 📄 Describe
프로젝트 README.md를 작성한다. 

### ✅ Tasks

- [x]  LiveShare README.md 공동작업 

### 🙋🏻 More
*No response*

**Comment by zldnlto** [comment]
![11](https://github.com/user-attachments/assets/aae70179-86d2-4999-9aa3-f24a1974d218)

**Comment by woojoung1217** [comment]
![image](https://github.com/user-attachments/assets/20677450-dc1e-414f-a24d-6e77fe163699)

**Comment by woojoung1217** [comment]
![image](https://github.com/user-attachments/assets/f5b2c8eb-98f0-4f48-840f-2d2282ec5641)

**Comment by zldnlto** [comment]
![tmuchtalkfff](https://github.com/user-attachments/assets/436de2fe-1a2b-4e4b-ad49-1a5e828c33d5)

**Comment by woojoung1217** [comment]
https://private-user-images.githubusercontent.com/34205465/361800991-f5b2c8eb-98f0-4f48-840f-2d2282ec5641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjE2MzksIm5iZiI6MTcyNDc2MTMzOSwicGF0aCI6Ii8zNDIwNTQ2NS8zNjE4MDA5OTEtZjViMmM4ZWItOThmMC00ZjQ4LTg0MGYtMmQyMjgyZWM1NjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEyMjIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMDVlMTM1ZjNkM2IwOGVlZmQwYjg4ZGQyMTMwZTBmOGYyN2RlYWFhY2VjMjZlYjIwMDU4ZTYyZWM5ODcwZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RwZZBM5tC4U78aBRsZb-_pQLUKHgufeeOQ_M_43exOE

**Comment by zldnlto** [comment]
![하이라이토긔](https://github.com/user-attachments/assets/c0a63f68-e24d-439e-aad3-b19444512b70)

**Comment by zldnlto** [comment]
<img width="45" alt="프사1" src="https://github.com/user-attachments/assets/62f4a12d-4242-4e7c-b9a9-c583c06c0c02">
<img width="45" alt="프사2" src="https://github.com/user-attachments/assets/393ee171-1410-4aa8-965c-49d0faf18637">
<img width="45" alt="프사3" src="https://github.com/user-attachments/assets/8212a3ae-83dc-454e-a46b-b4cae3f59b9c">

**Comment by zldnlto** [comment]
![image](https://github.com/user-attachments/assets/866cf082-cd2d-4d37-ace2-8d2c3ab16812)

**Comment by woojoung1217** [comment]
![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/f3dc146f-186e-4b34-ab82-a0bcf1b1ef3f/0b9e7adf-5cae-4392-bf73-3c0528e2ab9c/image.png)
